spring.datasource.username=root
spring.datasource.password=senha123
spring.datasource.url=jdbc:mysql://localhost:3306/gestao-usuario-banco
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always